### ISSUE TITLE
`./MacOS/` helper for macOS broken

### ISSUE THREAD

**Issue by galegosimpatico** [anura-engine/anura#303]
By https://github.com/anura-engine/anura/commit/189909b84c79bdc846da73facd047cb2df943c70.

Relevant footage at https://discord.com/channels/156241487938584577/447492980098596876/736320487239581747.

Compile output at https://discord.com/channels/156241487938584577/447492980098596876/736282384001138785.

It took me a while to check, but I think my Mac build might be broken too. We'll know for sure when Jetrel checks his.

**Comment by galegosimpatico** [comment]
Similarly to what @spixi and/or ein_waschechter_yugioh_lappen [commented][0], **can't build https://github.com/anura-engine/anura/commit/189909b84c79bdc846da73facd047cb2df943c70 while can build parent rev https://github.com/anura-engine/anura/commit/914784c01e6e2f679033c85d0fdce7a1630059dc**...

... to this some oddity which I don't remember having seen before...

<img width="1280" alt="Screenshot 2020-07-25 at 13 38 44" src="https://user-images.githubusercontent.com/53513496/88456231-4bba7980-ce7c-11ea-9da5-36fac82bdd7e.png">

... or maybe I saw something like that but long ago... or at some other game...

... which IDK if could perfectly be my fault, as I've been away from building for many months lately now. But you can guess this's a laptop featuring a retina display.

Cheers,

[0]: https://discord.com/channels/156241487938584577/447492980098596876/736320487239581747

**Comment by DDR0** [comment]
Hm, I had to do some tweaking to make the windows build work. I might have messed it up. :grimacing:

**Comment by DDR0** [comment]
Hm, I had to do some tweaking to make the windows build work. I have evidently messed something up. :grimacing:

**Comment by DDR0** [comment]
OK, 914784c01 is definitely the last git revision that will build on Linux. I've committed a few fixes just now for my work in 189909b84 - 2c6d721b7..196ac1d3b - but I can't get it to link on my Ubuntu machine now. :confused: (I did have to install libglm-dev here, but I'm not sure if that was caused by the windows commit or not.)

I can't reproduce the half-sized-level issue here with 914784c01 at the moment.

Sorry for the trouble. I really should have done this on a branch, apparently. >_<

**Comment by galegosimpatico** [comment]
> [...]
> 
> Sorry for the trouble. I really should have done this on a branch, apparently. >_<

Everything that could have gone wrong, it went. This should have lived on a branch, that branch must have been under strict-most CI audits and under several people's eyes, specially right before merging. There's no CI even for `trunk` right now, you are obviously not to blame. Luckily traffic is at an all times low and this is going to resolve mostly unknown.

**Comment by DDR0** [comment]
Indeed. I would pull it into its own branch otherwise. 🙂

**Comment by DDR0** [comment]
Ah, somehow I'd messed up my ccache. After running `ccache -C` as suggested by Dave, things are working here again. I'd like to get confirmation that the mac build works and that *someone* else can compile on Linux before marking this as closed.

![image](https://user-images.githubusercontent.com/862627/89005427-46649100-d2b9-11ea-86d0-9c2f8a6ac0d6.png)

**Comment by galegosimpatico** [comment]
> [...] I'd like to get confirmation that the mac build works and that someone else can compile on Linux before marking this as closed.

I'm at Xcode, yes I still can't see my mac build working normally. That's not surprising, as there hasn't been any changes suggesting that it might work now. I also think you don't even know how its failed compiler output looks. How could you have a fix?

It told, and it still tells, `'SDL.h' file not found`, for instance, at `logger.hpp`.

**Comment by DDR0** [comment]
I had assumed the errors were the same, my apologies.

**Comment by galegosimpatico** [comment]
> Ah, somehow I'd messed up my ccache. After running `ccache -C` as suggested by Dave, things are working here again. I'd like to get confirmation that the mac build works and that _someone_ else can compile on Linux before marking this as closed.
> 
> ![image](https://user-images.githubusercontent.com/862627/89005427-46649100-d2b9-11ea-86d0-9c2f8a6ac0d6.png)

Oh, that's nice.

Would you please share an `ldd anura` output for that? I guess it could be necessary in order to unbreak the mac stuff.

Thanks in advance.

**Comment by GSchuemann** [comment]
Can confirm that it compiles succesfully on Ubuntu 18.04 and also runs. 

EDIT:
@galegosimpatico 
ldd anura
	linux-vdso.so.1 (0x00007fffb83fb000)
	libGL.so.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f2e23fc3000)
	libGLEW.so.2.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libGLEW.so.2.0 (0x00007f2e23d2e000)
	libSDL2_image-2.0.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0 (0x00007f2e23afe000)
	libSDL2_ttf-2.0.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so.0 (0x00007f2e238f6000)
	libSDL2-2.0.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0 (0x00007f2e235c4000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2e233a7000)
	libfreetype.so.6 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f2e230f3000)
	libcairo.so.2 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f2e22dd6000)
	libvorbisfile.so.3 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libvorbisfile.so.3 (0x00007f2e22bce000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2e229c6000)
	libboost_regex.so.1.65.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libboost_regex.so.1.65.1 (0x00007f2e226be000)
	libboost_system.so.1.65.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1 (0x00007f2e224b9000)
	libboost_filesystem.so.1.65.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1 (0x00007f2e2229f000)
	libboost_locale.so.1.65.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libboost_locale.so.1.65.1 (0x00007f2e21fb6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2e21d97000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2e21a0e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2e21670000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2e21458000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2e21067000)
	libGLX.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f2e20e36000)
	libGLdispatch.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f2e20b80000)
	libpng16.so.16 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f2e2094e000)
	libjpeg.so.8 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f2e206e6000)
	libtiff.so.5 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f2e2046f000)
	libwebp.so.6 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libwebp.so.6 (0x00007f2e20206000)
	libasound.so.2 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f2e1feff000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2e1fcfb000)
	libpulse.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libpulse.so.0 (0x00007f2e1faab000)
	libsndio.so.6.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libsndio.so.6.1 (0x00007f2e1f89b000)
	libX11.so.6 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f2e1f563000)
	libXext.so.6 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f2e1f351000)
	libXcursor.so.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f2e1f147000)
	libXinerama.so.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f2e1ef44000)
	libXi.so.6 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f2e1ed34000)
	libXrandr.so.2 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f2e1eb29000)
	libXss.so.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libXss.so.1 (0x00007f2e1e925000)
	libXxf86vm.so.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f2e1e71f000)
	libwayland-egl.so.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007f2e1e51d000)
	libwayland-client.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f2e1e30e000)
	libwayland-cursor.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007f2e1e106000)
	libxkbcommon.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f2e1dec7000)
	libpixman-1.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f2e1dc22000)
	libfontconfig.so.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f2e1d9dd000)
	libxcb-shm.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f2e1d7da000)
	libxcb.so.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f2e1d5b2000)
	libxcb-render.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f2e1d3a5000)
	libXrender.so.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f2e1d19b000)
	libvorbis.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007f2e1cf70000)
	libogg.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007f2e1cd67000)
	libicui18n.so.60 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libicui18n.so.60 (0x00007f2e1c8c6000)
	libicuuc.so.60 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007f2e1c50e000)
	libboost_thread.so.1.65.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1 (0x00007f2e1c2e9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2e256b7000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f2e1c0c3000)
	libjbig.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007f2e1beb5000)
	libpulsecommon-11.1.so => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-11.1.so (0x00007f2e1bc37000)
	libdbus-1.so.3 => /snap/argentumage/x26/lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f2e1b9ea000)
	libbsd.so.0 => /snap/argentumage/x26/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f2e1b7d5000)
	libXfixes.so.3 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f2e1b5cf000)
	libffi.so.6 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f2e1b3c7000)
	libexpat.so.1 => /snap/argentumage/x26/lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f2e1b195000)
	libXau.so.6 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f2e1af91000)
	libXdmcp.so.6 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f2e1ad8b000)
	libicudata.so.60 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007f2e191e2000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f2e18f5e000)
	libwrap.so.0 => /snap/argentumage/x26/lib/x86_64-linux-gnu/libwrap.so.0 (0x00007f2e18d54000)
	libsndfile.so.1 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libsndfile.so.1 (0x00007f2e18adb000)
	libasyncns.so.0 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libasyncns.so.0 (0x00007f2e188d5000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f2e186b9000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f2e1839d000)
	libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007f2e18183000)
	libFLAC.so.8 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007f2e17f0c000)
	libvorbisenc.so.2 => /snap/argentumage/x26/usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007f2e17c63000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f2e17a48000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f2e17833000)

If that is what you wanted ;)

**Comment by DDR0** [comment]
Here's mine, if it helps to have a non-snap version. https://pasteall.org/rm2Z

**Comment by galegosimpatico** [comment]
Good, OK thanks.

I wonder why only one of those links Boost "system".

**Comment by galegosimpatico** [comment]
Future proof archive of temporary https://github.com/anura-engine/anura/issues/303#issuecomment-667311481:

```
$ ldd anura
linux-vdso.so.1 (0x00007ffd64561000)
libGL.so.1 => /lib/x86_64-linux-gnu/libGL.so.1 (0x00007ff869f44000)
libGLEW.so.2.1 => /lib/x86_64-linux-gnu/libGLEW.so.2.1 (0x00007ff869e9a000)
libSDL2_image-2.0.so.0 => /lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0 (0x00007ff869e77000)
libSDL2_ttf-2.0.so.0 => /lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so.0 (0x00007ff869e6e000)
libSDL2-2.0.so.0 => /lib/x86_64-linux-gnu/libSDL2-2.0.so.0 (0x00007ff869d19000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff869cfd000)
libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007ff869c3c000)
libcairo.so.2 => /lib/x86_64-linux-gnu/libcairo.so.2 (0x00007ff869b19000)
libvorbisfile.so.3 => /lib/x86_64-linux-gnu/libvorbisfile.so.3 (0x00007ff869b0e000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff869b03000)
libboost_regex.so.1.71.0 => /lib/x86_64-linux-gnu/libboost_regex.so.1.71.0 (0x00007ff869a03000)
libboost_filesystem.so.1.71.0 => /lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0 (0x00007ff8699e5000)
libboost_locale.so.1.71.0 => /lib/x86_64-linux-gnu/libboost_locale.so.1.71.0 (0x00007ff869905000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff8698e2000)
libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff869701000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff8695b2000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff869597000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff8693a5000)
/lib64/ld-linux-x86-64.so.2 (0x00007ff86b55c000)
libGLdispatch.so.0 => /lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007ff8692eb000)
libGLX.so.0 => /lib/x86_64-linux-gnu/libGLX.so.0 (0x00007ff8692b7000)
libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007ff86927f000)
libjpeg.so.8 => /lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007ff8691fa000)
libtiff.so.5 => /lib/x86_64-linux-gnu/libtiff.so.5 (0x00007ff869179000)
libwebp.so.6 => /lib/x86_64-linux-gnu/libwebp.so.6 (0x00007ff868f10000)
libasound.so.2 => /lib/x86_64-linux-gnu/libasound.so.2 (0x00007ff868e17000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff868e11000)
libpulse.so.0 => /lib/x86_64-linux-gnu/libpulse.so.0 (0x00007ff868dbc000)
libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007ff868c7f000)
libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007ff868c6a000)
libXcursor.so.1 => /lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007ff868c5d000)
libXinerama.so.1 => /lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007ff868c56000)
libXi.so.6 => /lib/x86_64-linux-gnu/libXi.so.6 (0x00007ff868c44000)
libXrandr.so.2 => /lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007ff868c37000)
libXss.so.1 => /lib/x86_64-linux-gnu/libXss.so.1 (0x00007ff868c32000)
libXxf86vm.so.1 => /lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007ff868c2b000)
libwayland-egl.so.1 => /lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007ff868c26000)
libwayland-client.so.0 => /lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007ff868c13000)
libwayland-cursor.so.0 => /lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007ff868c08000)
libxkbcommon.so.0 => /lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007ff868bc6000)
libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007ff868b1f000)
libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007ff868ad8000)
libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007ff868ad1000)
libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007ff868aa7000)
libxcb-render.so.0 => /lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007ff868a98000)
libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007ff86888e000)
libvorbis.so.0 => /lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007ff868860000)
libogg.so.0 => /lib/x86_64-linux-gnu/libogg.so.0 (0x00007ff868853000)
libicui18n.so.66 => /lib/x86_64-linux-gnu/libicui18n.so.66 (0x00007ff868552000)
libicuuc.so.66 => /lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007ff86836c000)
libboost_thread.so.1.71.0 => /lib/x86_64-linux-gnu/libboost_thread.so.1.71.0 (0x00007ff868340000)
libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007ff868297000)
liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007ff868270000)
libjbig.so.0 => /lib/x86_64-linux-gnu/libjbig.so.0 (0x00007ff868060000)
libpulsecommon-13.99.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-13.99.so (0x00007ff867fe0000)
libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007ff867f8f000)
libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007ff867f87000)
libffi.so.7 => /lib/x86_64-linux-gnu/libffi.so.7 (0x00007ff867f7b000)
libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007ff867f4b000)
libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007ff867f42000)
libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007ff867f3c000)
libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007ff867f34000)
libicudata.so.66 => /lib/x86_64-linux-gnu/libicudata.so.66 (0x00007ff866473000)
libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007ff8663c4000)
libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (0x00007ff8663b8000)
libsndfile.so.1 => /lib/x86_64-linux-gnu/libsndfile.so.1 (0x00007ff86633b000)
libasyncns.so.0 => /lib/x86_64-linux-gnu/libasyncns.so.0 (0x00007ff866135000)
libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007ff86611b000)
liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007ff8660f8000)
libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007ff865fda000)
libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007ff865fbd000)
libFLAC.so.8 => /lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007ff865f7f000)
libvorbisenc.so.2 => /lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007ff865ed4000)
libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007ff865eb8000)
libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007ff865e93000)
```

**Comment by DDR0** [comment]
Issue #287 may relate to the macOS build.

**Comment by galegosimpatico** [comment]
I'm diving into this, see if I can fix it before Jet; but I'm legendarily terrible at anything Xcode, so we'll see.

**Comment by galegosimpatico** [comment]
> Issue #287 may relate to the macOS build.

It would be good, to support it, but we aren't really using `xcodebuild`.

**Comment by spixi** [comment]
It is at least compilable and runnable on Gentoo GNU/Linux, but shows some errors when compiling shaders. I did not test multiplayer.

```
	linux-vdso.so.1 (0x00007ffe1b9a0000)
	libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f3957d37000)
	libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007f3957cb0000)
	libGLEW.so.1.13 => /usr/lib64/libGLEW.so.1.13 (0x00007f3957c17000)
	libGLU.so.1 => /usr/lib64/libGLU.so.1 (0x00007f3957b54000)
	libSDL2_image-2.0.so.0 => /usr/lib64/libSDL2_image-2.0.so.0 (0x00007f3957931000)
	libSDL2_ttf-2.0.so.0 => /usr/lib64/libSDL2_ttf-2.0.so.0 (0x00007f3957729000)
	libSDL2-2.0.so.0 => /usr/lib64/libSDL2-2.0.so.0 (0x00007f395742b000)
	libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007f39573e5000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f39573c3000)
	libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007f39572dc000)
	libcairo.so.2 => /usr/lib64/libcairo.so.2 (0x00007f395715a000)
	libogg.so.0 => /usr/lib64/libogg.so.0 (0x00007f3957150000)
	libvorbis.so.0 => /usr/lib64/libvorbis.so.0 (0x00007f3957101000)
	libvorbisfile.so.3 => /usr/lib64/libvorbisfile.so.3 (0x00007f39570f4000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f39570ea000)
	libvpx.so.5 => /usr/lib64/libvpx.so.5 (0x00007f3956df8000)
	libboost_regex.so.1.65.0 => /usr/lib64/libboost_regex.so.1.65.0 (0x00007f3956caa000)
	libboost_system.so.1.65.0 => /usr/lib64/libboost_system.so.1.65.0 (0x00007f3956ca4000)
	libboost_filesystem.so.1.65.0 => /usr/lib64/libboost_filesystem.so.1.65.0 (0x00007f3956c84000)
	libboost_locale.so.1.65.0 => /usr/lib64/libboost_locale.so.1.65.0 (0x00007f3956b70000)
	libicui18n.so.64 => /usr/lib64/libicui18n.so.64 (0x00007f3956836000)
	libicuuc.so.64 => /usr/lib64/libicuuc.so.64 (0x00007f3956632000)
	libicudata.so.64 => /usr/lib64/libicudata.so.64 (0x00007f3954bed000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3954bcd000)
	libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libstdc++.so.6 (0x00007f3954956000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f3954820000)
	libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libgcc_s.so.1 (0x00007f3954806000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f395464d000)
	libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f3954620000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f395461b000)
	libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007f39545df000)
	libxcb-dri3.so.0 => /usr/lib64/libxcb-dri3.so.0 (0x00007f39545d9000)
	libxcb-xfixes.so.0 => /usr/lib64/libxcb-xfixes.so.0 (0x00007f39545d0000)
	libxcb-present.so.0 => /usr/lib64/libxcb-present.so.0 (0x00007f39545cc000)
	libxcb-sync.so.1 => /usr/lib64/libxcb-sync.so.1 (0x00007f39545c3000)
	libxshmfence.so.1 => /usr/lib64/libxshmfence.so.1 (0x00007f39545c0000)
	libglapi.so.0 => /usr/lib64/libglapi.so.0 (0x00007f395458c000)
	libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f3954574000)
	libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x00007f3954570000)
	libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007f3954569000)
	libX11-xcb.so.1 => /usr/lib64/libX11-xcb.so.1 (0x00007f3954566000)
	libxcb-glx.so.0 => /usr/lib64/libxcb-glx.so.0 (0x00007f3954549000)
	libxcb-dri2.so.0 => /usr/lib64/libxcb-dri2.so.0 (0x00007f3954541000)
	libXxf86vm.so.1 => /usr/lib64/libXxf86vm.so.1 (0x00007f395453a000)
	libdrm.so.2 => /usr/lib64/libdrm.so.2 (0x00007f3954525000)
	libjpeg.so.62 => /usr/lib64/libjpeg.so.62 (0x00007f395449c000)
	libtiff.so.5 => /usr/lib64/libtiff.so.5 (0x00007f395440e000)
	libasound.so.2 => /usr/lib64/libasound.so.2 (0x00007f3954310000)
	libpulse.so.0 => /usr/lib64/libpulse.so.0 (0x00007f39540be000)
	libXcursor.so.1 => /usr/lib64/libXcursor.so.1 (0x00007f39540b0000)
	libXinerama.so.1 => /usr/lib64/libXinerama.so.1 (0x00007f39540ac000)
	libXi.so.6 => /usr/lib64/libXi.so.6 (0x00007f3954098000)
	libXrandr.so.2 => /usr/lib64/libXrandr.so.2 (0x00007f395408b000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f3954072000)
	libpixman-1.so.0 => /usr/lib64/libpixman-1.so.0 (0x00007f3953f5e000)
	libfontconfig.so.1 => /usr/lib64/libfontconfig.so.1 (0x00007f3953f0a000)
	libEGL.so.1 => /usr/lib64/libEGL.so.1 (0x00007f3953ece000)
	libxcb-shm.so.0 => /usr/lib64/libxcb-shm.so.0 (0x00007f3953ec9000)
	libxcb-render.so.0 => /usr/lib64/libxcb-render.so.0 (0x00007f3953eb9000)
	libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007f3953eaa000)
	libmvec.so.1 => /lib64/libmvec.so.1 (0x00007f3953e7e000)
	libboost_chrono.so.1.65.0 => /usr/lib64/libboost_chrono.so.1.65.0 (0x00007f3953e78000)
	libboost_thread.so.1.65.0 => /usr/lib64/libboost_thread.so.1.65.0 (0x00007f3953e47000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f395a1f6000)
	libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f3953e40000)
	libXdmcp.so.6 => /usr/lib64/libXdmcp.so.6 (0x00007f3953e38000)
	libpulsecommon-10.0.so => /usr/lib64/pulseaudio/libpulsecommon-10.0.so (0x00007f3953bb1000)
	libdbus-1.so.3 => /usr/lib64/libdbus-1.so.3 (0x00007f3953b5d000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f3953b52000)
	libgbm.so.1 => /usr/lib64/libgbm.so.1 (0x00007f3953b42000)
	libbsd.so.0 => /usr/lib64/libbsd.so.0 (0x00007f3953b27000)
	libICE.so.6 => /usr/lib64/libICE.so.6 (0x00007f3953b06000)
	libSM.so.6 => /usr/lib64/libSM.so.6 (0x00007f3953afc000)
	libXtst.so.6 => /usr/lib64/libXtst.so.6 (0x00007f3953af1000)
	libwrap.so.0 => /lib64/libwrap.so.0 (0x00007f3953ae5000)
	libsndfile.so.1 => /usr/lib64/libsndfile.so.1 (0x00007f3953a47000)
	libasyncns.so.0 => /usr/lib64/libasyncns.so.0 (0x00007f3953a41000)
	libFLAC.so.8 => /usr/lib64/libFLAC.so.8 (0x00007f39539df000)
	libvorbisenc.so.2 => /usr/lib64/libvorbisenc.so.2 (0x00007f395392d000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f3953915000)
```

```
WARN: ShadersOGL.cpp:859 : Auto-added '#version 120' to the top of 27a1eadc3a6340828cba2bc420faa0ca_vs shader to make it work.
ERROR: ShadersOGL.cpp:894 : Error compiling shader(5beca6a325ff425ba22f0cd1d324115b_fs): 0:18(18): error: no matching function for call to `max(int, float)'; candidates are:
0:18(18): error:    float max(float, float)
0:18(18): error:    vec2 max(vec2, float)
0:18(18): error:    vec3 max(vec3, float)
0:18(18): error:    vec4 max(vec4, float)
0:18(18): error:    vec2 max(vec2, vec2)
0:18(18): error:    vec3 max(vec3, vec3)
0:18(18): error:    vec4 max(vec4, vec4)
0:18(18): error:    int max(int, int)
0:18(18): error:    ivec2 max(ivec2, int)
0:18(18): error:    ivec3 max(ivec3, int)
0:18(18): error:    ivec4 max(ivec4, int)
0:18(18): error:    ivec2 max(ivec2, ivec2)
0:18(18): error:    ivec3 max(ivec3, ivec3)
0:18(18): error:    ivec4 max(ivec4, ivec4)
0:18(10): error: operands to arithmetic operators must be numeric

ERROR: ShadersOGL.cpp:894 : Error compiling shader(card_shadow_fs): 0:21(16): error: no matching function for call to `max(int, float)'; candidates are:
0:21(16): error:    float max(float, float)
0:21(16): error:    vec2 max(vec2, float)
0:21(16): error:    vec3 max(vec3, float)
0:21(16): error:    vec4 max(vec4, float)
0:21(16): error:    vec2 max(vec2, vec2)
0:21(16): error:    vec3 max(vec3, vec3)
0:21(16): error:    vec4 max(vec4, vec4)
0:21(16): error:    int max(int, int)
0:21(16): error:    ivec2 max(ivec2, int)
0:21(16): error:    ivec3 max(ivec3, int)
0:21(16): error:    ivec4 max(ivec4, int)
0:21(16): error:    ivec2 max(ivec2, ivec2)
0:21(16): error:    ivec3 max(ivec3, ivec3)
0:21(16): error:    ivec4 max(ivec4, ivec4)
0:22(36): warning: `ratio' used uninitialized
0:24(16): error: no matching function for call to `max(int, float)'; candidates are:
0:24(16): error:    float max(float, float)
0:24(16): error:    vec2 max(vec2, float)
0:24(16): error:    vec3 max(vec3, float)
0:24(16): error:    vec4 max(vec4, float)
0:24(16): error:    vec2 max(vec2, vec2)
0:24(16): error:    vec3 max(vec3, vec3)
0:24(16): error:    vec4 max(vec4, vec4)
0:24(16): error:    int max(int, int)
0:24(16): error:    ivec2 max(ivec2, int)
0:24(16): error:    ivec3 max(ivec3, int)
0:24(16): error:    ivec4 max(ivec4, int)
0:24(16): error:    ivec2 max(ivec2, ivec2)
0:24(16): error:    ivec3 max(ivec3, ivec3)
0:24(16): error:    ivec4 max(ivec4, ivec4)
0:25(36): warning: `ratio' used uninitialized
```

**Comment by galegosimpatico** [comment]
I was able to compile back again by:

1. Taking back `ANURA_BASE/MacOS/` like how it was at parent rev of https://github.com/anura-engine/anura/commit/189909b84c79bdc846da73facd047cb2df943c70.
2. ~~Feeding Homebrew's Boost 1.72 binary libraries in the frog's `ANURA_BASE/MacOS/`.~~
3. Throwing Boost asio 1.72 into `external/include/boost/`.
4. Patching in this diff in boost asio (https://stackoverflow.com/questions/1123044/when-should-your-destructor-be-virtual via https://stackoverflow.com/questions/8764353/what-does-has-virtual-method-but-non-virtual-destructor-warning-mean-durin). I don't understand why:
```
diff --git a/external/include/boost/asio/impl/error.ipp b/external/include/boost/asio/impl/error.ipp
index 0dcb1257c..a45558b8c 100644
--- a/external/include/boost/asio/impl/error.ipp
+++ b/external/include/boost/asio/impl/error.ipp
@@ -49,6 +49,8 @@ public:
       return "A non-recoverable error occurred during database lookup";
     return "asio.netdb error";
   }
+
+  virtual ~netdb_category(){}
 };
 
 } // namespace detail
@@ -77,6 +79,8 @@ public:
       return "Socket type not supported";
     return "asio.addrinfo error";
   }
+
+  virtual ~addrinfo_category(){}
 };
 
 } // namespace detail
@@ -111,6 +115,7 @@ public:
       return "The descriptor does not fit into the select call's fd_set";
     return "asio.misc error";
   }
+  virtual ~misc_category(){}
 };
 
 } // namespace detail
```

It was obvious the `ANURA_BASE/MacOS/` thing relies on `ANURA_BASE/external/include/`.

Wouldn't link because missing references to names in regex, filesystem etc. I'm currently tackling those, but still no linking, no running.

Even if it ran, this is very far from a satisfactory fix, but it's what I'm able to blitz.

**Does the windows version rely on `ANURA_BASE/external/include/` too?**

**Did you pass anything new into `ANURA_BASE/external/include/boost/`, in https://github.com/anura-engine/anura/commit/189909b84c79bdc846da73facd047cb2df943c70? If so, do you remember which exact Boost version was used?** Last I've read, it's claiming for unfound references to a namespace/class `re_detail_107100_...` (regex implementation details for version 1.71.0?).

**Comment by DDR0** [comment]
Dumb question, will boost 1.73 work?

The Windows version does rely on `ANURA_BASE/external/include/`.

Boost version changes are as follows:
```diff
-#define BOOST_LIB_VERSION "1_56"
+#define BOOST_LIB_VERSION "1_71"
```

**Comment by galegosimpatico** [comment]
Excellent, that must be why it can't find 107100 implementation detail, but might be apparently finding anything else. It must be finding 107200 implementation detail instead.

Now that I couldn't successfully blitz Homebrew's Boost binaries into it, because unluckily we are on different mileages, I shall go [the RTFM way][0] (should have done later anyway, for security). That should work, but I guess it'll take me several days.

Then I shall remember to update this broken link to it: https://github.com/anura-engine/anura/blob/f0a10fc8ed1361a91ed47d19911de6fcab24f733/MacOS/Read%20Me.txt#L5

And I hope there won't be anything else.

[0]: https://github.com/frogatto/frogatto/wiki/Compiling-Frogatto-on-Mac-OS-X

**Comment by galegosimpatico** [comment]
> [...] shows some errors when compiling shaders. [...]
> 
> ```
> [...]
> ```
> 
> ```
> WARN: ShadersOGL.cpp:859 : Auto-added '#version 120' to the top of 27a1eadc3a6340828cba2bc420faa0ca_vs shader to make it work.
> ERROR: ShadersOGL.cpp:894 : Error compiling shader(5beca6a325ff425ba22f0cd1d324115b_fs): 0:18(18): error: no matching function for call to `max(int, float)'; candidates are:
> 0:18(18): error:    float max(float, float)
> 0:18(18): error:    vec2 max(vec2, float)
> 0:18(18): error:    vec3 max(vec3, float)
> 0:18(18): error:    vec4 max(vec4, float)
> 0:18(18): error:    vec2 max(vec2, vec2)
> 0:18(18): error:    vec3 max(vec3, vec3)
> 0:18(18): error:    vec4 max(vec4, vec4)
> 0:18(18): error:    int max(int, int)
> 0:18(18): error:    ivec2 max(ivec2, int)
> 0:18(18): error:    ivec3 max(ivec3, int)
> 0:18(18): error:    ivec4 max(ivec4, int)
> 0:18(18): error:    ivec2 max(ivec2, ivec2)
> 0:18(18): error:    ivec3 max(ivec3, ivec3)
> 0:18(18): error:    ivec4 max(ivec4, ivec4)
> 0:18(10): error: operands to arithmetic operators must be numeric
> 
> ERROR: ShadersOGL.cpp:894 : Error compiling shader(card_shadow_fs): 0:21(16): error: no matching function for call to `max(int, float)'; candidates are:
> 0:21(16): error:    float max(float, float)
> 0:21(16): error:    vec2 max(vec2, float)
> 0:21(16): error:    vec3 max(vec3, float)
> 0:21(16): error:    vec4 max(vec4, float)
> 0:21(16): error:    vec2 max(vec2, vec2)
> 0:21(16): error:    vec3 max(vec3, vec3)
> 0:21(16): error:    vec4 max(vec4, vec4)
> 0:21(16): error:    int max(int, int)
> 0:21(16): error:    ivec2 max(ivec2, int)
> 0:21(16): error:    ivec3 max(ivec3, int)
> 0:21(16): error:    ivec4 max(ivec4, int)
> 0:21(16): error:    ivec2 max(ivec2, ivec2)
> 0:21(16): error:    ivec3 max(ivec3, ivec3)
> 0:21(16): error:    ivec4 max(ivec4, ivec4)
> 0:22(36): warning: `ratio' used uninitialized
> 0:24(16): error: no matching function for call to `max(int, float)'; candidates are:
> 0:24(16): error:    float max(float, float)
> 0:24(16): error:    vec2 max(vec2, float)
> 0:24(16): error:    vec3 max(vec3, float)
> 0:24(16): error:    vec4 max(vec4, float)
> 0:24(16): error:    vec2 max(vec2, vec2)
> 0:24(16): error:    vec3 max(vec3, vec3)
> 0:24(16): error:    vec4 max(vec4, vec4)
> 0:24(16): error:    int max(int, int)
> 0:24(16): error:    ivec2 max(ivec2, int)
> 0:24(16): error:    ivec3 max(ivec3, int)
> 0:24(16): error:    ivec4 max(ivec4, int)
> 0:24(16): error:    ivec2 max(ivec2, ivec2)
> 0:24(16): error:    ivec3 max(ivec3, ivec3)
> 0:24(16): error:    ivec4 max(ivec4, ivec4)
> 0:25(36): warning: `ratio' used uninitialized
> ```

Must be related to https://github.com/davewx7/citadel/issues/202.
